/*
2022-06-13
 Jason
game over class
*/
package GUIs;

/**
 *
 * @author matth
 */
public class InstructionsWindow extends javax.swing.JFrame {

    private static MenuWindow menu;
    
    
    public InstructionsWindow(MenuWindow m) {
        initComponents();
        this.setLocationRelativeTo(null);
        txtAreaInstructions.setEditable(false);
        menu = m; //save menu screen in variable
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblInstructions = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaInstructions = new javax.swing.JTextArea();
        btnBack = new javax.swing.JButton();
        lblBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblInstructions.setFont(new java.awt.Font("Ravie", 0, 48)); // NOI18N
        lblInstructions.setForeground(new java.awt.Color(0, 255, 51));
        lblInstructions.setText("Instructions");

        txtAreaInstructions.setColumns(20);
        txtAreaInstructions.setFont(new java.awt.Font("OCR A Extended", 0, 18)); // NOI18N
        txtAreaInstructions.setLineWrap(true);
        txtAreaInstructions.setRows(5);
        txtAreaInstructions.setText("Journal \n24-05-73\n\nWhat is this place?  \nThere are creatures here, and they're not friendly. I found that killing them is good for THE SCORE. \n\nFind the keys. It's needed to enter the dungeon.\n\nControls I have figured out:\nW - move up\nA - move left\nS - move down\nD - move right\nY - swing sword\nP - freezes time somehow?\n\nI need to get through the dungeon. IMPORTANT: WATCH OUT FOR THE —\n");
        txtAreaInstructions.setWrapStyleWord(true);
        jScrollPane1.setViewportView(txtAreaInstructions);

        btnBack.setFont(new java.awt.Font("Poor Richard", 0, 24)); // NOI18N
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        lblBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUIs/InstructionsBackground.jpg"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(180, 180, 180)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 830, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(1100, 1100, 1100)
                .addComponent(btnBack))
            .addGroup(layout.createSequentialGroup()
                .addGap(382, 382, 382)
                .addComponent(lblInstructions, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(lblBackground)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(590, 590, 590)
                .addComponent(btnBack))
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(lblInstructions))
            .addComponent(lblBackground, javax.swing.GroupLayout.PREFERRED_SIZE, 660, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        this.setVisible(false); //make menu visible      
        menu.setVisible(true); //make instructions invisible
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBackground;
    private javax.swing.JLabel lblInstructions;
    private javax.swing.JTextArea txtAreaInstructions;
    // End of variables declaration//GEN-END:variables
}
